### PR TITLE
pass xml string to "Call SOAP Method With XML" instead of xml file

### PR DESCRIPTION
**Pull request by hadi-jabbari**
I want to pass XML string to the "Call SOAP Method With XML" keyword because I need a different representation of one file in several test cases and scenarios.
Also, I add a test case to test this functionality

### CODE REVIEW

**Comment by samuelpcabral** [comment]
Hi @hadi-jabbari

I didn't fully understand your need to pass an XML string instead of XML .. could you share this template that gives an error in the library?

I ask this because in your change if I enter "else" the code will fail.

example:

```
xml = "some_String"

if str(xml).find("<") != -1:
    raw_text_xml = str(xml)
else:
    raw_text_xml = etree.fromstring(xml)
```
of course I shouldn't go into this part of the code, but since we have no control over whether people will pass real XML as a file, this could cause an error in the library.

We chose to use etree.fromstring (xml) to have an XML object instead of its string.

If for some reason you really need the string instead of the object, my idea would be to create a new argument in the keyword.

If you can give more details I would appreciate it.

Thank you.

**Comment by hadi-jabbari** [comment]
Hi dear @samuelpcabral 

Actually, I need to call the keyword same as below:

`Call SOAP Method With XML  <sample><Id>1</Id><sample>`

Consider you don't have an XML file but you have an XML string. In my case, I have to change an XML after that send it to the SOAP service, I don't want to save several XML files and I prefer to change them on the fly.

In addition, I have run the tests and all of them had been passed, and the above functionality is working as well.
If you think it's better to add a new keyword for this functionality tell me to add it.

I am looking forward to hearing from you about what we should do exactly

Thanks for your respond

**Comment by samuelpcabral** [comment]
I see... i think is better create a new keyword, something like "Call SOAP Method With String XML" I can do it now and put in a new version.

**Comment by samuelpcabral** [comment]
Hi @hadi-jabbari i push the new "Call SOAP Method With String XML" to your branch.. see if this new keyword will work for you...

**Pull request closed without merging**
